# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver import ChromeOptions

class Test_checkout():
  def setup_method(self, method):
    #configure chrome in headless to work in containers
    options = ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--disable-extensions')
    options.add_argument("--no-sandbox")
    self.driver = webdriver.Remote('http://localhost:4444/wd/hub', options.to_capabilities())

    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1116, 864)
    self.driver.find_element(By.CSS_SELECTOR, ".site-menu > li:nth-child(2) > a").click() 

  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_is_item_size_s(self):
    pass

  def test_is_item_colour_green(self):
    pass
  
